Update yolo3_one_file_to_detect_them_all.py
cause of the line 10, error's happen

```python
Traceback (most recent call last):
  File "yolo3_one_file_to_detect_them_all.py", line 10, in <module>
    np.set_printoptions(threshold=np.nan)
  File "/home/syscon/.local/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 259, in set_printoptions
    floatmode, legacy)
  File "/home/syscon/.local/lib/python3.5/site-packages/numpy/core/arrayprint.py", line 95, in _make_options_dict
    raise ValueError("threshold must be non-NAN, try "
ValueError: threshold must be non-NAN, try sys.maxsize for untruncated representation
```

code should be changed like this propose.